[color-theme]
name = ""

[color-theme.base]
white = "#ffffff"
black = "#1b2026"
grey = "#707f8c"
blue = "#2729d8"
red = "#d22e1a"
yellow = "#dac97b"
orange = "#78492b"
green = "#3e8086"
purple = "#814fb8"
cyan = "#b2d7ff"
magenta = "#ad3da5"

[color-theme.syntax]
attribute = "$orange"
builtinType = "$purple"
comment = "$grey"
constant = "$orange"
constructor = "$magenta"
embedded = "$cyan"
enum = "$green"
enum-member = "#027daf"
enumMember = "#027daf"
escape = "$green"
field = "#027daf"
function = "#027daf"
"function.method" = "#027daf"
interface = "#6bdfff"
keyword = "$magenta"
"keyword.control" = "$magenta"
method = "#027daf"
number = "$yellow"
property = "#027daf"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$magenta"
string = "$red"
"string.escape" = "$red"
struct = "$green"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$green"
"type.builtin" = "$purple"
typeAlias = "$cyan"
variable = "$white"
"variable.other.member" = "#027daf"

[color-theme.ui]
"activity.background" = "#21252B"
"activity.current" = "$black"
"completion.background" = "#21252B"
"completion.current" = "#2C313A"
"editor.background" = "$white"
"editor.caret" = "$black"
"editor.current_line" = "#ecf5ff"
"editor.dim" = "$grey"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$black"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$white"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#ffeaad66"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#21252B"
"inlay_hint.background" = "#528abF37"
"inlay_hint.foreground" = "$white"
"lapce.border" = "#bcbec1"
"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.icon.active" = "#567282"
"lapce.icon.inactive" = "#525254"
"lapce.plugin.author" = "$grey"
"lapce.plugin.description" = "$grey"
"lapce.plugin.name" = "$black"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"
"lapce.remote.local" = "#4078F2"
"lapce.scroll_bar" = "#7f7f7f"
"lapce.tab.active.background" = "#f3f2f1"
"lapce.tab.active.foreground" = "$black"
"lapce.tab.active.underline" = "#528BFF"
"lapce.tab.inactive.background" = "#e7e7e6"
"lapce.tab.inactive.foreground" = "$black"
"lapce.tab.inactive.underline" = "#528BFF77"
"lapce.tab.separator" = "#c9c9c8"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#d3d4d6"
"palette.current.background" = "#ca4985"
"palette.current.foreground" = "$white"
"palette.foreground" = "$black"
"panel.background" = "#d3d4d6"
"panel.current.background" = "#0b84ff"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#5C6370"
"panel.foreground" = "#ffffff"
"panel.foreground.dim" = "#b8b0a7"
"panel.hovered.background" = "#383431"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C6370"
"source_control.added" = "#007aff"
"source_control.modified" = "#007aff"
"source_control.removed" = "#007aff"
"status.background" = "$white"
"status.foreground" = "$black"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$white"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "$grey"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "$white"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$black"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$black"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
